JCCCAppProj/Models/JobPosting.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace JCCCAppProj.Models
{
    public class JobPosting
    {
        [Key]
        public int JobPostingID { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Created Date")]
        public Nullable<System.DateTime> createdDate { get; set; }

        [StringLength(75)]
        [Display(Name = "Job Description")]
        public string JobDescription { get; set; }

        [StringLength(64)]
        [Display(Name = "Job Title")]
        public string JobTitle { get; set; }

        [Display(Name = "Number of Openings")]
        public Nullable <int> NumOpenings { get; set; }

        [Display(Name = "Hours Per Week")]
        public Nullable<int> HoursPerWeek { get; set; }

        [Display(Name = "Salary")]
        public Nullable<decimal> WageSalary { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Start Date")]
        public Nullable<System.DateTime> StartDate { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "End Date")]
        public Nullable<System.DateTime> EndDate { get; set; }

        [StringLength(300)]
        [Display(Name = "Job Qualifications")]
        public string Qualifications { get; set; }

        [StringLength(100)]
        [Display(Name = "Application Instructions")]
        public string ApplicationInstructions { get; set; }

        [StringLength(64)]
        [Display(Name = "Application Website")]
        public string ApplicationWebsite { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Expiration Date")]
        public Nullable<System.DateTime> ExpirationDate { get; set; }

        [StringLength(64)]
        [Display(Name = "Job Type")]
        public string JobType { get; set; }

        [ForeignKey("Industry")]
        public int IndustryID { get; set; }
        public virtual Industry Industry { get; set; }

        [ForeignKey("Employer")]
        public int EmployerID { get; set; }
        public virtual Employer Employer { get; set; }
        

    }
}

JCCCAppProj/Controllers/JobPostingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JCCCAppProj.Models;
using JCCCAppProj.ViewModel;

using System.Linq.Dynamic;




    namespace JCCCAppProj.Controllers
    {
        public class JobPostingsController : Controller
        {
            private ApplicationDbContext db = new ApplicationDbContext();

           
            // GET: JobPostings
            public ActionResult Index()
            {
                var jobPostings = db.JobPostings.Include(j => j.Employer).Include(j => j.Industry);
                return View(jobPostings.ToList());
            }
            
           
            // GET: JobPostings/Details/5
            public ActionResult Details(int? id)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                JobPosting jobPosting = db.JobPostings.Find(id);
                if (jobPosting == null)
                {
                    return HttpNotFound();
                }
                return View(jobPosting);
            }

            [AllowAnonymous]
            // GET: JobPostings/Create
            public ActionResult Create()
            {
                ViewBag.EmployerID = new SelectList(db.Employers, "EmployerID", "Id");
                ViewBag.IndustryID = new SelectList(db.Industries, "IndustryID", "IndustryName");
                return View();
            }

            // POST: JobPostings/Create
            // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
            // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
            [HttpPost]
            [ValidateAntiForgeryToken]
            public ActionResult Create([Bind(Include = "JobPostingID,createdDate,JobDescription,JobTitle,NumOpenings,HoursPerWeek,WageSalary,StartDate,EndDate,Qualifications,ApplicationInstructions,ApplicationWebsite,ExpirationDate,JobType,IndustryID,EmployerID")] JobPosting jobPosting)
            {
                if (ModelState.IsValid)
                {
                    db.JobPostings.Add(jobPosting);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                ViewBag.EmployerID = new SelectList(db.Employers, "EmployerID", "Id", jobPosting.EmployerID);
                ViewBag.IndustryID = new SelectList(db.Industries, "IndustryID", "IndustryName", jobPosting.IndustryID);
                return View(jobPosting);
            }

            // GET: JobPostings/Edit/5
            public ActionResult Edit(int? id)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                JobPosting jobPosting = db.JobPostings.Find(id);
                if (jobPosting == null)
                {
                    return HttpNotFound();
                }
                ViewBag.EmployerID = new SelectList(db.Employers, "EmployerID", "Id", jobPosting.EmployerID);
                ViewBag.IndustryID = new SelectList(db.Industries, "IndustryID", "IndustryName", jobPosting.IndustryID);
                return View(jobPosting);
            }

            // POST: JobPostings/Edit/5
            // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
            // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
            [HttpPost]
            [ValidateAntiForgeryToken]
            public ActionResult Edit([Bind(Include = "JobPostingID,createdDate,JobDescription,JobTitle,NumOpenings,HoursPerWeek,WageSalary,StartDate,EndDate,Qualifications,ApplicationInstructions,ApplicationWebsite,ExpirationDate,JobType,IndustryID,EmployerID")] JobPosting jobPosting)
            {
                if (ModelState.IsValid)
                {
                    db.Entry(jobPosting).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                ViewBag.EmployerID = new SelectList(db.Employers, "EmployerID", "Id", jobPosting.EmployerID);
                ViewBag.IndustryID = new SelectList(db.Industries, "IndustryID", "IndustryName", jobPosting.IndustryID);
                return View(jobPosting);
            }

            // GET: JobPostings/Delete/5
            public ActionResult Delete(int? id)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                JobPosting jobPosting = db.JobPostings.Find(id);
                if (jobPosting == null)
                {
                    return HttpNotFound();
                }
                return View(jobPosting);
            }

            // POST: JobPostings/Delete/5
            [HttpPost, ActionName("Delete")]
            [ValidateAntiForgeryToken]
            public ActionResult DeleteConfirmed(int id)
            {
                JobPosting jobPosting = db.JobPostings.Find(id);
                db.JobPostings.Remove(jobPosting);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            // GET: JobPostings/Search/5
            /* public ActionResult Search()
             {

                ViewBag.IndustriesIndustryName = new SelectList(db.Industries, "IndustryName", "IndustryName");
                 //ViewBag.IndustriesIndustryName = new SelectList(db.Industries, "IndustryID", "IndustryName");
                 var Industries = db.JobPostings.Include(j => j.Employer).Include(j => j.Industry);
                 return View(Industries.ToList());

             }


             // POST: JobPostings/Search/5
             [HttpPost]
             public ActionResult Search(string IndustriesIndustryName)
             {
                 ViewBag.IndustriesIndustryName = new SelectList(db.Industries, "IndustryName", "IndustryName");
                 //ViewBag.IndustriesIndustryName = new SelectList(db.Industries, "IndustryID", "IndustryName");

                 var Industries = db.JobPostings.Include(j => j.Employer).Include(j => j.Industry).Where(i => i.Industry.IndustryName == IndustriesIndustryName);



                 return View(Industries.ToList());

             }*/

            public ActionResult JobSearch(SearchViewModel model)
            {
                //Bind Industry drop down in search

                ViewBag.IndustriesIndustryName = new SelectList(db.Industries, "IndustryName", "IndustryName");


            //Get posting details
            //model.Companies = db.Companies
            model.JobPostings = db.JobPostings

                .Where(
                p =>
                (model.JobTitle == null || p.JobTitle.Contains(model.JobTitle))
                && (model.IndustryName == null || p.Industry.IndustryName == model.IndustryName)
              // && (model.CompanyName == null || p.Employer.Companies.Contains(model.CompanyName))
                && (model.JobType == null || p.JobType.Contains(model.JobType)))
               
                    .OrderBy(model.Sort + " " + model.SortDir)
                    .Skip((model.Page - 1) * model.PageSize)
                    .Take(model.PageSize)
                    .ToList();


                // total records for paging
                model.TotalRecords = db.JobPostings
                    .Count(x =>
                        (model.JobTitle == null || x.JobTitle.Contains(model.JobTitle))
                        && (model.JobType == null || x.JobType == model.JobType)
                        //&& (model.CompanyName == null || x.Employer.Companies.Equals(model.CompanyName))
                        && (model.IndustryName == null || x.Industry.IndustryName == model.IndustryName)
                        );

                return View(model);

            }

            public ActionResult SearchDetails(int? id)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                JobPosting jobPosting = db.JobPostings.Find(id);
                if (jobPosting == null)
                {
                    return HttpNotFound();
                }
                return View(jobPosting);
            }


            protected override void Dispose(bool disposing)
            {
                if (disposing)
                {
                    db.Dispose();
                }
                base.Dispose(disposing);
            }
        }
    }

JCCCAppProj/Views/JobPostings/Create.cshtml
@model JCCCAppProj.Models.JobPosting

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>JobPosting</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.createdDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.createdDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.createdDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.JobDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.JobDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.JobDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.JobTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.JobTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.JobTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumOpenings, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumOpenings, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumOpenings, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HoursPerWeek, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HoursPerWeek, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HoursPerWeek, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WageSalary, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WageSalary, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WageSalary, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Qualifications, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Qualifications, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Qualifications, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ApplicationInstructions, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ApplicationInstructions, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ApplicationInstructions, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ApplicationWebsite, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ApplicationWebsite, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ApplicationWebsite, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExpirationDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExpirationDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExpirationDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.JobType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.JobType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.JobType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IndustryID, "IndustryID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IndustryID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IndustryID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmployerID, "EmployerID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EmployerID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EmployerID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

JCCCAppProj/Views/JobPostings/Delete.cshtml
@model JCCCAppProj.Models.JobPosting

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>JobPosting</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Employer.Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Employer.Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Industry.IndustryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Industry.IndustryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.createdDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.createdDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JobDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JobDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JobTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JobTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumOpenings)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumOpenings)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HoursPerWeek)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoursPerWeek)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WageSalary)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WageSalary)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Qualifications)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Qualifications)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApplicationInstructions)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApplicationInstructions)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApplicationWebsite)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApplicationWebsite)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExpirationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExpirationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JobType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JobType)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

JCCCAppProj/Views/JobPostings/Details.cshtml
@model JCCCAppProj.Models.JobPosting

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Details</h2>

<div>
    <h4>JobPosting</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Employer.Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Employer.Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Industry.IndustryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Industry.IndustryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.createdDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.createdDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JobDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JobDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JobTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JobTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumOpenings)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumOpenings)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HoursPerWeek)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoursPerWeek)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WageSalary)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WageSalary)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Qualifications)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Qualifications)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApplicationInstructions)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApplicationInstructions)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApplicationWebsite)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApplicationWebsite)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExpirationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExpirationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JobType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JobType)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.JobPostingID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

JCCCAppProj/Views/JobPostings/JobSearch.cshtml
@model JCCCAppProj.ViewModel.SearchViewModel

@{
    ViewBag.Title = "JobSearch";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>JobSearch</h2>

@using (Html.BeginForm("JobSearch", "JobPostings", FormMethod.Get))
{
    
    <div class="row">

        <div class="form-horizontal">
            <div class="col-lg-3">
                @Html.TextBoxFor(m => m.JobTitle, new { @class = "form-control", @placeholder = "Job Title" })
            </div>
            <div class="col-lg-3">
                @Html.TextBoxFor(m => m.JobType, new { @class = "form-control", @placeholder = "Job Type" })
                   </div>
            <div class="col-lg-3">
                @Html.TextBoxFor(m => m.CompanyName, new { @class = "form-control", @placeholder = "Company" })
            </div>
                <div class="col-lg-push-12">
                    @Html.DropDownListFor(m => m.IndustryName, new SelectList(ViewBag.IndustriesIndustryName, "Value", "Text"),
                   "All Categories", new { @class = "form-control", @placeholder = "Your Major/Industry" })

                </div>
                <div class="col-lg-push5">
                    <button type="submit" class="btn btn-success">
                        <span class="glyphicon glyphicon-search"></span>
                    </button>

                    
                </div>
            </div>
    </div>

    <div style="margin-top:17px;">
        @{
            var grid = new WebGrid(
                                canPage: true,
                                rowsPerPage: Model.PageSize,
                                canSort: true,
                                ajaxUpdateContainerId: "grid");

            grid.Bind(Model.JobPostings, rowCount: Model.TotalRecords, autoSortAndPage: false);
            grid.Pager(WebGridPagerModes.All);

            @grid.GetHtml(htmlAttributes: new { id = "grid" },
        fillEmptyRows: false,
        tableStyle: "table table-bordered table-hover",
        mode: WebGridPagerModes.All,
        columns: grid.Columns(
              grid.Column("JobTitle", "Job Title", style: "col-lg-6"),
              grid.Column("Industry.IndustryName", "Industry", style: "col-lg-2"),
              //grid.Column("CompanyName", "Company", style: "col-lg-6"),
              grid.Column("JobType", "Job Type", style: "col-lg-3"),
              grid.Column("ApplicationWebsite", "Application Website", style: "col-lg-6"),
              grid.Column("createdDate", "Date", style: "col - lg - 6"),

              grid.Column(header: "Job Details", canSort: false, style: "action",
                format: @<text>
                @Html.Raw("<a data-modal='' href='/JobPostings/SearchDetails/" + item.JobPostingID + "' JobPostingID='" + item.JobPostingID + "' title='Detail'> <span class='glyphicon glyphicon-search'> </span> </a>")
                
                </text>)
        ));
        }
    </div>
      
            }

JCCCAppProj/Views/JobPostings/Search.cshtml
@model IEnumerable<JCCCAppProj.Models.JobPosting>

@{
    ViewBag.Title = "Search";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Search for Jobs</h2>

@using (Html.BeginForm())
{
    <p>Search by Major/Industry:

        @Html.DropDownList("IndustriesIndustryName", null, htmlAttributes: new { @class = "form-control" })

    
       
    <br />
        <input class = "btn btn-primary btn-lg" type="submit" value="Search" />
    </p>

    <table class="table">
        <tr>
           
            <th>
                @Html.DisplayNameFor(model => model.Industry.IndustryName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.JobTitle)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.ApplicationWebsite)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.JobType)
            </th>
            <th></th>

            <th>
                @Html.DisplayNameFor(model => model.createdDate)
            </th>
            <th>
                Details
            </th>
            
            
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                
                <td>
                    @Html.DisplayFor(modelItem => item.Industry.IndustryName)
                </td>
               
                
                <td>
                    @Html.DisplayFor(modelItem => item.JobTitle)
                </td>
               
               
                <td>
                    @Html.DisplayFor(modelItem => item.ApplicationWebsite)
                </td>
                
                <td>
                    @Html.DisplayFor(modelItem => item.JobType)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.createdDate)
                </td>
                <td>
                    
                    @Html.ActionLink("Job Details", "SearchDetails", new { id = item.JobPostingID }) |
                    
                </td>
            </tr>
        }

    </table>
}